name: pandas_ecosystem
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - rise

  - numpy=1.16.2
  - pandas=0.24.2
  - xarray=0.11.3
  - vaex=1.0.0
  - static-frame=0.3.0
  - dask=1.2.0
